name: CICD

on:
  push:
    branches: [main,master]
    
jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Set Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Install Dependencies
        run : npm install
      - name: Test Project
        run: npm run build
      - name: Deploy to Azure Web app Service
        uses: azure/webapps-deploy@v2
        with:
         app-name: node-rn
         publish-profile: ${{ secrets.azureWebAppPublishProfile }}
